# Project
version=0.1.0
group=com.payangar.moredarkness
java_version=25

# Common
minecraft_version=26.2
mod_name=More Darkness
mod_author=Payangar
mod_id=more_darkness
license=MIT
credits=Inspired by True Darkness (grondag) and Fog (IMB11)
description=Enhances Minecraft darkness with realistic moon phases, pitch black caves and depth fog.
minecraft_version_range=[26.2]
neo_form_version=26.2-2

# Fabric
fabric_version=0.155.2+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.25-beta

# YACL
yacl_version=3.9.6+26.2

# ModMenu
modmenu_version=20.0.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
